In [2]:
import numpy as np

In [3]:
list1 = [1, 2, 3, 4, 5]
matrix1 = [[1, 2, 3], [2, 3, 7], [5, 4, 1]]

np_array = np.array(list1)
print(np_array, end='\n\n')

np_matrix = np.array(matrix1)
print(np_matrix)

[1 2 3 4 5]

[[1 2 3]
 [2 3 7]
 [5 4 1]]


In [4]:
zero_matrix = np.zeros((3, 3))
zero_matrix_2 = np.zeros(3)
one_matrix = np.ones((3, 4, 5))

print(zero_matrix, end='\n\n')
print(zero_matrix_2, end='\n\n')
print(one_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[0. 0. 0.]

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [5]:
v1 = np.arange(0, 13)
v2 = np.arange(0, 13, 2)

print(v1, end='\n\n')
print(v2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12]

[ 0  2  4  6  8 10 12]


In [6]:
l1 = np.linspace(0, 10, 5)
l1

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [7]:
i1 = np.eye(5)

print(i1, end='\n\n')

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]



In [8]:
random_matrix = np.random.rand(3,3)
random_matrix

array([[0.84803345, 0.94247168, 0.65253491],
       [0.81540411, 0.12483858, 0.04605737],
       [0.54926001, 0.41270389, 0.5028542 ]])

In [9]:
random_matrix_2 = np.random.randn(3,3)
random_matrix_2

array([[ 0.04973105,  0.11754554,  2.03373159],
       [-0.88160507, -0.15167201, -2.83413116],
       [ 1.09313917, -1.29700326, -0.48814657]])

In [10]:
random_matrix_3 = np.random.randint(1, 100,(3, 3))
random_matrix_3

array([[ 9, 66, 89],
       [34, 41,  1],
       [14, 30, 69]], dtype=int32)

In [11]:
arr = np.random.randint(1, 100, 15)
arr

array([67, 47, 52, 82, 20, 90, 28, 95, 23, 57, 24, 54, 52, 84, 90],
      dtype=int32)

In [12]:
arr.reshape(5, 3)

array([[67, 47, 52],
       [82, 20, 90],
       [28, 95, 23],
       [57, 24, 54],
       [52, 84, 90]], dtype=int32)

In [13]:
arr.reshape(3, 5)

array([[67, 47, 52, 82, 20],
       [90, 28, 95, 23, 57],
       [24, 54, 52, 84, 90]], dtype=int32)

In [14]:
print(arr.max())
print(arr.mean())
print(arr.min(), end='\n\n')

print(arr.argmax())
print(arr.argmin())

95
57.666666666666664
20

7
4


In [15]:
arr = arr.reshape(3, 5)

print(arr.argmax())
print(arr.argmin())

7
4


In [16]:
print(arr.shape)
print(arr.dtype)
print(arr.ndim)
print(arr.size)

arr2 = np.random.randint(1, 100, (3, 5, 4, 2, 3))

print(arr2.ndim)
print(arr2.shape)
print(arr2.size)

(3, 5)
int32
2
15
5
(3, 5, 4, 2, 3)
360


In [17]:
np.empty((3, 3))

array([[ 0.04973105,  0.11754554,  2.03373159],
       [-0.88160507, -0.15167201, -2.83413116],
       [ 1.09313917, -1.29700326, -0.48814657]])

In [18]:
np.sort(arr)

array([[20, 47, 52, 67, 82],
       [23, 28, 57, 90, 95],
       [24, 52, 54, 84, 90]], dtype=int32)

In [19]:
# np.concat((arr, arr2))
# Must have same number of dimensions

arr0 = np.random.randint(1, 100, (3, 3))
arr01 = np.random.randint(1, 100, (3, 3))

arr3 = np.concat((arr0, arr01))
print(arr3, end='\n\n')
print(arr3.ndim)
print(arr3.shape, end='\n\n')

print(arr3.transpose(), end='\n\n')
print(np.sort(arr3), end='\n\n')
print(np.sort(arr3.transpose()))

# All entries aren't sorted, instead each list under the matrix is sorted

[[21 70 76]
 [63 47 83]
 [67 77 75]
 [42 67 19]
 [61 27 12]
 [43 39 78]]

2
(6, 3)

[[21 63 67 42 61 43]
 [70 47 77 67 27 39]
 [76 83 75 19 12 78]]

[[21 70 76]
 [47 63 83]
 [67 75 77]
 [19 42 67]
 [12 27 61]
 [39 43 78]]

[[21 42 43 61 63 67]
 [27 39 47 67 70 77]
 [12 19 75 76 78 83]]


In [20]:
a = np.random.randint(1, 10, (3, 3))
a

array([[4, 9, 6],
       [1, 6, 9],
       [4, 6, 3]], dtype=int32)

In [21]:
print(a[a > 5])

[9 6 6 9 6]


In [22]:
print(a[a % 2 != 0])

[9 1 9 3]


In [23]:
print(a[(a > 2) & (a < 8)])

[4 6 6 4 6 3]


In [24]:
x = np.arange(1, 49).reshape(4, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48]])

In [25]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16],
        [25, 26, 27, 28],
        [37, 38, 39, 40]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20],
        [29, 30, 31, 32],
        [41, 42, 43, 44]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24],
        [33, 34, 35, 36],
        [45, 46, 47, 48]])]

In [26]:
np.vsplit(x, 2)

[array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]]),
 array([[25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36],
        [37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48]])]

In [33]:
predictions = [1, 2, 4, 5, 1, 3, 2, 4, 1.2, 0]
label = [0, 3, 1, 2, 3, 1, 5, 6, 7 , 2]

npreds = np.array(predictions)
nlabel = np.array(label)

n = len(predictions)

avg = (1/n) * np.sum(np.square(npreds - nlabel))

avg

np.float64(7.864000000000001)