In [1]:
import numpy as np

In [4]:
list1 = [1, 2, 3, 4, 5]
matrix1 = [[1, 2, 3], [2, 3, 7], [5, 4, 1]]

np_array = np.array(list1)
print(np_array, end='\n\n')

np_matrix = np.array(matrix1)
print(np_matrix)

[1 2 3 4 5]

[[1 2 3]
 [2 3 7]
 [5 4 1]]


In [7]:
zero_matrix = np.zeros((3, 3))
zero_matrix_2 = np.zeros(3)
one_matrix = np.ones((3, 4, 5))

print(zero_matrix, end='\n\n')
print(zero_matrix_2, end='\n\n')
print(one_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[0. 0. 0.]

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [11]:
v1 = np.arange(0, 13)
v2 = np.arange(0, 13, 2)

print(v1, end='\n\n')
print(v2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12]

[ 0  2  4  6  8 10 12]


In [21]:
l1 = np.linspace(0, 10, 5)
l1

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [23]:
i1 = np.eye(5)

print(i1, end='\n\n')

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]



In [29]:
random_matrix = np.random.rand(3,3)
random_matrix

array([[0.37613915, 0.52604176, 0.61993483],
       [0.00390634, 0.23520574, 0.86292052],
       [0.84824461, 0.56858499, 0.97370773]])

In [31]:
random_matrix_2 = np.random.randn(3,3)
random_matrix_2

array([[-0.07061194,  0.71196115, -1.16946857],
       [ 0.39950086,  0.45307056,  0.14382247],
       [ 0.43544345, -0.3166096 ,  0.18713934]])

In [34]:
random_matrix_3 = np.random.randint(1, 100,(3, 3))
random_matrix_3

array([[56, 10, 68],
       [ 2, 13, 91],
       [96, 62, 69]], dtype=int32)

In [37]:
arr = np.random.randint(1, 100, 15)
arr

array([48, 41, 60, 38,  1, 61, 81, 43, 22, 15, 64, 72, 81, 22, 29],
      dtype=int32)

In [39]:
arr.reshape(5, 3)

array([[48, 41, 60],
       [38,  1, 61],
       [81, 43, 22],
       [15, 64, 72],
       [81, 22, 29]], dtype=int32)

In [40]:
arr.reshape(3, 5)

array([[48, 41, 60, 38,  1],
       [61, 81, 43, 22, 15],
       [64, 72, 81, 22, 29]], dtype=int32)

In [43]:
print(arr.max())
print(arr.mean())
print(arr.min(), end='\n\n')

print(arr.argmax())
print(arr.argmin())

81
45.2
1

6
4


In [46]:
arr = arr.reshape(3, 5)

print(arr.argmax())
print(arr.argmin())

6
4


In [51]:
print(arr.shape)
print(arr.dtype)
print(arr.ndim)
print(arr.size)

arr2 = np.random.randint(1, 100, (3, 5, 4, 2, 3))

print(arr2.ndim)
print(arr2.shape)
print(arr2.size)

(3, 5)
int32
2
15
5
(3, 5, 4, 2, 3)
360


In [54]:
np.empty((3, 3))

array([[-0.07061194,  0.71196115, -1.16946857],
       [ 0.39950086,  0.45307056,  0.14382247],
       [ 0.43544345, -0.3166096 ,  0.18713934]])

In [55]:
np.sort(arr)

array([[ 1, 38, 41, 48, 60],
       [15, 22, 43, 61, 81],
       [22, 29, 64, 72, 81]], dtype=int32)

In [ ]:
# np.concat((arr, arr2))
# Must have same number of dimensions

arr0 = np.random.randint(1, 100, (3, 3))
arr01 = np.random.randint(1, 100, (3, 3))

arr3 = np.concat((arr0, arr01))
print(arr3, end='\n\n')
print(arr3.ndim)
print(arr3.shape, end='\n\n')

print(arr3.transpose(), end='\n\n')
print(np.sort(arr3), end='\n\n')
print(np.sort(arr3.transpose()))

# All entries aren't sorted, instead each list under the matrix is sorted

[[91 70 22]
 [97 73 16]
 [92 28 32]
 [38 64 61]
 [36 66 45]
 [62 48 25]]

2
(6, 3)

[[91 97 92 38 36 62]
 [70 73 28 64 66 48]
 [22 16 32 61 45 25]]

[[22 70 91]
 [16 73 97]
 [28 32 92]
 [38 61 64]
 [36 45 66]
 [25 48 62]]

[[36 38 62 91 92 97]
 [28 48 64 66 70 73]
 [16 22 25 32 45 61]]


In [74]:
a = np.random.randint(1, 10, (3, 3))
a

array([[8, 5, 6],
       [1, 3, 7],
       [5, 5, 2]], dtype=int32)

In [75]:
print(a[a > 5])

[8 6 7]


In [76]:
print(a[a % 2 != 0])

[5 1 3 7 5 5]


In [80]:
print(a[(a > 2) & (a < 8)])

[5 6 3 7 5 5]


In [89]:
x = np.arange(1, 49).reshape(4, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48]])

In [90]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16],
        [25, 26, 27, 28],
        [37, 38, 39, 40]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20],
        [29, 30, 31, 32],
        [41, 42, 43, 44]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24],
        [33, 34, 35, 36],
        [45, 46, 47, 48]])]

In [94]:
np.vsplit(x, 2)

[array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]]),
 array([[25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36],
        [37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48]])]